In [1]:
import numpy as np
import math
pointA = np.array((3,4))
pointB = np.array((1,1))
np.linalg.norm(pointA - pointB)

3.605551275463989

In [31]:
# ex 2
x = np.array((3,4))
y = np.array((-1,-1))
imp = np.sqrt(x.T @ x * y.T @ y)
deimp = x.T @ y
print(imp,deimp)
r = deimp/imp
#dot_p = np.dot(x,y)
print(r)
print(np.arccos(r))

7.0710678118654755 -7
-0.9899494936611665
2.9996955989856287


In [1]:
print(math.degrees(0))                       #0 radians == 0 degrees
print(math.degrees(math.pi/2))               #pi/2 radians is 90 degrees
print(math.degrees(math.pi))                 #pi radians is 180 degrees
print(math.degrees(math.pi+(math.pi/2)))     #pi+pi/2 radians is 270 degrees
print(math.degrees(math.pi+math.pi))         #2*pi radians is 360 degrees

0.0
90.0
180.0
270.0
360.0


In [2]:
print(math.radians(0))           #0 degrees == 0 radians
print(math.radians(90))          #90 degrees is pi/2 radians
print(math.radians(180))         #180 degrees is pi radians
print(math.radians(270))        #270 degrees is pi+(pi/2) radians
print(math.radians(360))         #360 degrees is 2*pi radians

0.0
1.5707963267948966
3.141592653589793
4.71238898038469
6.283185307179586


In [18]:
r

-1.0101525445522108

In [24]:
np.arccos(4/5)

0.6435011087932843

In [20]:
np.arccos(r)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in arccos
  """Entry point for launching an IPython kernel.


nan

In [22]:
#ex 3
x = np.array((3,4))
y = np.array((1,1))
z = x - y
print(z)
distance = np.sqrt(z.T @ z)
print(distance)

[2 3]
3.605551275463989


In [34]:
#ex 5
x = np.array((1,2,3))
y = np.array((-1,0,8))
z = x - y
imp = np.sqrt(x.T @ x * z.T @ z)
deimp = x.T @ z
print(imp,deimp)
r = deimp/imp
print(r)
print(np.arccos(r))

21.494185260204677 -9
-0.41871789467931186
2.002829357226812


In [35]:
a = np.array([1,0])
b = np.array([0,1])
I = np.array([[1,0],[0,1]])
print(a.T@I@b)

0


In [36]:
a = np.array([1,1])
I = np.array([[1,-0.5],[-0.5,1]])
print(a.T@I@a)

1.0


In [37]:
a = np.array([1,-1,3])
I = np.array([[2,1,0],[1,2,-1],[0,-1,2]])
print(a.T@I@a)

26


In [39]:
a = np.array([1/2,-1,-1/2])
b = np.array([0,1,0])
I = np.array([[2,1,0],[1,2,-1],[0,-1,2]])
z=a-b
print(z.T@I@z)

5.0


In [42]:
a = np.array([-1,1])
I = np.array([[5,-1],[-1,5]])
print(a.T@I@a)

12


In [47]:
a = np.array([4,2,1])
b = np.array([0,1,0])
I = np.array([[2,1,0],[1,2,-1],[0,-1,2]])
print(np.sqrt(a.T@I@b))

2.6457513110645907


In [44]:
a = np.array([-1,-1,-1])
I = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(a.T@I@a)

3


In [52]:
 
a = np.array([1,1])
b = np.array([-1,1])
I = np.array([[2,0],[0,1]])
v = a.T@I@b
d = (a.T@a)*(b.T@b)
print(np.arccos(v/d))

1.8234765819369751


In [75]:
a = np.array([1,1])
b = np.array([-1,1])
I = np.array([[2,-1],[-1,4]])
v = a.T@I@b
d = np.sqrt((a.T@a)*(b.T@b))
print(v/d)
print(np.arccos(v/d))

1.0
0.0


In [90]:
x = np.array([2,3])
y = np.array([4,1])
z = x-y
dot = z.T@z
print(dot)
w = y-x
A = np.array([[1,-1/2],[-1/2,1]])
#dot = x.T@A@y
dot = (z.T@A@w)
print(dot)

8
-12.0


### Quiz - Angles between vectors using a non-standard inner product

In [107]:
#Ex 1
x = np.array([1,1])
y = np.array([-1,1])
A = np.array([[2,-1],[-1,4]])
dot = (x.T@A@y)
d = np.sqrt((x.T@A@x)*(y.T@A@y))
print(np.arccos(dot/d))

1.2094292028881888


In [115]:
#Ex 2
x = np.array([0,-1])
y = np.array([1,1])
A = np.array([[1,-1/2],[-1/2,5]])
dot = (x.T@A@y)
d = np.sqrt((x.T@A@x)*(y.T@A@y))
print(np.arccos(dot/d))

2.6905658417935308


In [116]:
#EX 3
x = np.array([2,2])
y = np.array([-2,-2])
A = np.array([[2,1],[1,4]])
dot = (x.T@A@y)
d = np.sqrt((x.T@A@x)*(y.T@A@y))
print(np.arccos(dot/d))

3.141592653589793


In [113]:
#Ex 4
x = np.array([1,1])
y = np.array([1,-1])
A = np.array([[1,0],[0,5]])
dot = (x.T@A@y)
d = np.sqrt((x.T@A@x)*(y.T@A@y))
print(np.arccos(dot/d))

2.300523983021863


In [112]:
#Ex 5
x = np.array([1,1,1])
y = np.array([2,-1,0])
A = np.array([[1,0,0],[0,2,-1],[0,-1,3]])
dot = (x.T@A@y)
d = np.sqrt((x.T@A@x)*(y.T@A@y))
print(np.arccos(dot/d))

1.3652273956337226


## Week 3

In [58]:
# ex1
b = np.array([1,2,2])
print(np.outer(b, b))
print(b@b.T)

[[1 2 2]
 [2 4 4]
 [2 4 4]]
9


In [60]:
#ex2
pi_x = np.array([1,1,1])
b = np.array([3,0,4])
x = pi_x*b.T*b.T
print(x)
pi_x2=1/13*np.outer(x,b).T@b
print(pi_x2)
# pi_x2 * ||b||**2=b.T@b

[ 9  0 16]
[21.  0. 28.]


3) Now, we compute the reconstruction error, i.e., the distance between the original data point and its projection onto a lower-dimensional subspace.
Assume our original data point is [1,1,1] and its projection is 1/9 [5,10,10].
What is the reconstruction error?

In [2]:
x = np.array([1,1,1])
y = np.array([5,10,10])
z = x-1/9*y
distance = np.sqrt(z.T@z)
distance

0.4714045207910317

### Project 3D data onto a 2D subspace

In [98]:
#ex1
from numpy.linalg import inv
x = np.array([6,0,0])
b1 = np.array([1,1,1])
b2 = np.array([0,1,2])
B = np.array([[1,0],[1,1],[1,2]])
lambda_ = inv(B.T@B)@B.T@x
print("lambda",lambda_)
pi_u_x = lambda_[0]*b1+lambda_[1]*b2
print("pi_u_x is:",pi_u_x)
print("projection matrix is:1/6*",6*B@inv(B.T@B)@B.T)

lambda [ 5. -3.]
pi_u_x is: [ 5.  2. -1.]
projection matrix is:1/6* [[ 5.  2. -1.]
 [ 2.  2.  2.]
 [-1.  2.  5.]]


In [99]:
#ex2
from numpy.linalg import inv
x = np.array([3,2,2])
b1 = np.array([1,0,0])
b2 = np.array([0,1,1])
B = np.array([[1,0],[0,1],[0,1]])
lambda_ = inv(B.T@B)@B.T@x
print("lambda",lambda_)
pi_u_x = lambda_[0]*b1+lambda_[1]*b2
print("pi_u_x is:",pi_u_x)
print("projection matrix is:1/6*",6*B@inv(B.T@B)@B.T)

lambda [3. 2.]
pi_u_x is: [3. 2. 2.]
projection matrix is:1/6* [[6. 0. 0.]
 [0. 3. 3.]
 [0. 3. 3.]]


In [119]:
#ex3
from numpy.linalg import inv
x = np.array([12,0,0])
b1 = np.array([1,1,1])
b2 = np.array([0,1,2])
B = np.array([[1,0],[1,1],[1,2]])
lambda_ = inv(B.T@B)@B.T@x
print("lambda",lambda_)
pi_u_x = lambda_[0]*b1+lambda_[1]*b2
print("pi_u_x",pi_u_x)
sqrt = np.sqrt(6)
b = sqrt*np.array([-10,-4,2])
print(b@b.T/b.T@b)
print(1/(720*3*2)*(b@b.T/b.T@b)*pi_u_x)

lambda [10. -6.]
pi_u_x [10.  4. -2.]
2160.0
[ 5.  2. -1.]


## Asig

In [124]:
def projection_matrix_1d(b):
    """Compute the projection matrix onto the space spanned by `b`
    Args:
        b: ndarray of dimension (D,), the basis for the subspace
    
    Returns:
        P: the projection matrix
    """
    D, = b.shape
    P = np.dot(b,b)/np.outer(b,b)
    return P